### ISSUE TITLE
[Project] Initial migration of data subset 

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-repository#50]
## Description ##

Migrate an initial subset of deposit data from the Fedora CORE repository into InvenioRDM.

## Deliverables ##

- Field mapping from Fedora CORE to InvenioRDM (DataCite)
- Export script from Fedora to CSV
- Import script from CSV to InvenioRDM
- InvenioRDM instance populated with sample CORE data 

## Target Timeline ##

- [x] #46 Find out how InvenioRDM team plans to handle pub info fields: 04-28
- [x] #25 Ian learn Fedora API: 05-03
- [x] #26 Write test export script from Fedora: 05-03
- [x] #52 Identify fields stored in WordPress: 05-03
- [x] #54 Decide how to include legacy URI in imported data: 05-05
- [x] #37 Match current metadata fields with DataCite fields: 05-05
- [x] #53 Write test WordPress export script to CSV: 05-10
- [x] #17 Implement required custom fields in Invenio JSON: 05-12 
- [x] #55 Configure basic UI for required custom fields in InvenioRDM: 05-12
- [x] #51 Write test import script from CSV to InvenioRDM: 05-17
- [x] #27 Migrate subset of CORE data for testing: 05-19
- [x] #28 Test migrated data and debug migration scripts: 05-24
- [x] #58 Decide how to handle file uploads in migration: 05-24

## Responsibilities ##

**Development Lead**:  Ian Scott

Other roles & responsibilities:

- Bonnie Russell: Helping to produce field mapping
