### ISSUE TITLE
[Project] UX and UI Design of new deposit form

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-repository#67]
## Description ##

TBD

*One-paragraph description of the project*

**Design document**: *Link to more detailed design document, if one exists*

## Deliverables ##

- *List of specific features or components that will be delivered by the project.*

## Target Timeline ##

- [ ] Production release: MM-DD
- [ ] Communication sent to users: MM-DD
- [ ] Help documentation in place: MM-DD
- [ ] Production-ready: MM-DD
- [ ] Testing complete: MM-DD
- [ ] Ready for testing: MM-DD
- [ ] *Other milestones as necessary*

## Responsibilities ##

**Development Lead**:  
**Community Lead**: 

Other roles & responsibilities:

-
