### ISSUE TITLE
[Project] Integrating Invenio with IDMS

### ISSUE THREAD

**Issue by monotasker** [MESH-Research/knowledge-commons-repository#8]
## Description ##

Integrate the InvenioRDM user registration and data with Commons IDMS.

## Deliverables ##

- Automate creation of Invenio users for Commons users
- Automate pulling of user data from Commons
- Configure Invenio login

## Target Timeline ##

- [x] Automate creation of Invenio users: 08-18
- [x] Automate pulling of user data from Commons: 08-25
- [x] Configure Invenio login: 08-25

## Responsibilities ##

**Development Lead**:  Ian Scott

Other roles & responsibilities:

- Mike Thicke: help with integration on Commons end
